%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\kurtb\Documents\MATLAB\AMS520-Project\Data\natgas.data.csv
%
% Auto-generated by MATLAB on 11-Oct-2021 22:56:36

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "STOCKS", "HDD_FORE", "CDD_FORE", "JFKTEMP", "CLTTEMP", "ORDTEMP", "HOUTEMP", "LAXTEMP", "NXT_CNG_STK"];
opts.VariableTypes = ["double", "double", "categorical", "categorical", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["HDD_FORE", "CDD_FORE"], "EmptyFieldRule", "auto");

% Import the data
natgas = readtable("C:\Users\kurtb\Documents\MATLAB\AMS520-Project\Data\natgas.data.csv", opts);


%% Clear temporary variables
clear opts